import mantine from 'eslint-config-mantine';
import { defineConfig } from 'eslint-define-config';
import tsParser from '@typescript-eslint/parser';
import eslintPluginI18next from 'eslint-plugin-i18next';

export default defineConfig([
  ...mantine,
  {
    ignores: ['**/*.{mjs,cjs,js,d.ts,d.mts}', './.storybook/main.ts'],
  },
  {
    files: ['**/*.story.tsx'],
    rules: { 'no-console': 'off' },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    rules: {
      quotes: ['error', 'single'],
      'jsx-quotes': ['error', 'prefer-single'],
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      'src/**/*.spec.ts',
      'src/**/*.spec.tsx',
      'src/**/*.story.tsx',
      'src/constants/**',
      'src/locals/**',
    ],
    plugins: { i18next: eslintPluginI18next },
    rules: {
      'i18next/no-literal-string': [
        process.env.HUSKY_I18N === '1' ? 'error' : 'warn',
        {
          framework: 'react',
          mode: 'jsx-only',
          message:
            'Use translation keys (e.g. t(...)) or values from src/constants instead of inline user-facing strings.',
          'jsx-attributes': {
            exclude: [
              'className',
              'class',
              'style',
              'alt',
              'aria-label',
              'shadow',
              'key',
              'htmlFor',
              'data-testid',
              'dataKey',
              'src',
              'width',
              'height',
              'viewBox',
              'xmlns',
              'fill',
              'stroke',
              'd',
              'preserveAspectRatio',
              'strokeLinecap',
              'strokeLinejoin',
              'strokeWidth',
              'cx',
              'cy',
              'r',
              'x',
              'y',
              'type',
              'target',
              'rel',
              'name',
              'id',
              'role',
              'component',
              'm',
              'loaderProps',
              'gap',
              'display',
              'flexWrap',
              'variant',
              'orientation',
              'from',
              'as',
              'color',
              'to',
              'path',
              'lang',
              'tabIndex',
              'size',
              'radius',
              'fw',
              'fz',
              'fs',
              'lh',
              'ta',
              'tt',
              'td',
              'c',
              'bg',
              'p',
              'px',
              'py',
              'pt',
              'pb',
              'pl',
              'pr',
              'mx',
              'my',
              'mt',
              'mb',
              'ml',
              'mr',
              'w',
              'h',
              'miw',
              'mih',
              'maw',
              'mah',
              'justify',
              'align',
              'wrap',
              'direction',
              'grow',
              'basis',
              'shrink',
              'span',
              'offset',
              'order',
              'colSpan',
              'rowSpan',
            ],
          },
          callees: {
            exclude: [
              '^console\\.',
              '^require$',
              '^import$',
              '^describe$',
              '^it$',
              '^test$',
              '^expect$',
              '^beforeEach$',
              '^afterEach$',
              '^beforeAll$',
              '^afterAll$',
              '^vi\\.',
              '^fn$',
              '^RegExp$',
              '^Error$',
              '^URL$',
              '^t$',
              '^i18n\\.t$',
              '^i18next\\.t$',
            ],
          },
          words: {
            exclude: [
              '^[^A-Za-z0-9]+$',
              '^\\/$',
              '^#[0-9a-fA-F]{3,8}$',
              '^rgba?\\(',
              '^\\d+(\\.\\d+)?(rem|px|em|vh|vw|%)$',
            ],
          },
        },
      ],
    },
  },
]);
