#!/usr/bin/env bash

pnpm run prettier:write
pnpm run eslint
echo "Running pre-commit hook"

commands=("pnpm build"
          "pnpm storybook:build"
         )

for cmd in "${commands[@]}"; do
  echo "Running: $cmd"
  $cmd || {
    echo "Command failed: $cmd"
    exit 1
  }
done

echo "All pre-commit checks passed!"



